### ISSUE TITLE
AttributeError: module 'spyx.axn' has no attribute 'Axon'

### ISSUE THREAD

**Issue by Dipendra7** [kmheckel/spyx#29]
I am experimenting cartpole with spiking neural network with spyx, but i got the following error. could you please assist?

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-25-40612f845aca>](https://localhost:8080/#) in <cell line: 4>()
      2 init_state = (jnp.zeros(64), jnp.zeros(2))
      3 policy = hk.without_apply_rng(hk.transform(controller))
----> 4 policy_params = policy.init(rng=key, x=adapter(obs), state=init_state)

2 frames
[<ipython-input-24-1dadbff2829c>](https://localhost:8080/#) in controller(x, state)
      7     core = hk.DeepRNN([
      8         hk.Linear(64, with_bias=False),
----> 9         snn.LIF(64, beta=0.8, activation=spyx.axn.Axon()),
     10         hk.Linear(2, with_bias=False),
     11         snn.LI(2)

AttributeError: module 'spyx.axn' has no attribute 'Axon'

**Comment by kmheckel** [comment]
Hi!

You just need to change `spyx.axn.Axon()` to `spyx.axn.arctan()` or any of the other surrogate activations. `spyx.axn.Axon()` is deprecated and I missed this when updating the examples and docs.

**Comment by Dipendra7** [comment]
Hi!
Thank you for prompt reply , I did change to spyx.axn.arctan() but I got following error: 
`TypeError                                 Traceback (most recent call last)
[<ipython-input-33-40612f845aca>](https://localhost:8080/#) in <cell line: 4>()
      2 init_state = (jnp.zeros(64), jnp.zeros(2))
      3 policy = hk.without_apply_rng(hk.transform(controller))
----> 4 policy_params = policy.init(rng=key, x=adapter(obs), state=init_state)

11 frames
[/usr/local/lib/python3.10/dist-packages/haiku/_src/base.py](https://localhost:8080/#) in get_parameter(name, shape, dtype, init)
    682   param = check_not_none(param, "Parameters cannot be `None`.")
    683 
--> 684   if param.shape != tuple(shape):
    685     raise ValueError(
    686         f"{fq_name!r} with retrieved shape {param.shape!r} does not match "

TypeError: 'int' object is not iterable`

**Comment by kmheckel** [comment]
Glad to hear it! I fixed the notebook on the docs as well to resolve this going forward.
